-- Schema for route-subsystem tests (H2, PostgreSQL mode)
DROP TABLE IF EXISTS route;
DROP TABLE IF EXISTS vehicle;
DROP TABLE IF EXISTS company;

CREATE TABLE company (
    company_id BIGINT PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    industry VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicle (
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    registration_no VARCHAR(50) NOT NULL UNIQUE,
    vehicle_type VARCHAR(50) NOT NULL,
    fuel_efficiency_kmpl DOUBLE NOT NULL,
    fuel_type VARCHAR(30) NOT NULL
);

CREATE TABLE route (
    route_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_city VARCHAR(100) NOT NULL,
    to_city VARCHAR(100) NOT NULL,
    path VARCHAR(1000) NOT NULL,
    total_distance DOUBLE NOT NULL,
    total_fuel_l DOUBLE NOT NULL,
    total_emission DOUBLE NOT NULL,
    algorithm_used VARCHAR(30) NOT NULL,
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO company(company_id, company_name, industry) VALUES
    (1, 'GreenFleet Logistics', 'Transport'),
    (2, 'RouteX', 'Logistics');

INSERT INTO vehicle(company_id, registration_no, vehicle_type, fuel_efficiency_kmpl, fuel_type) VALUES
    (1, 'MH12AB1234', 'truck', 8.0, 'diesel'),
    (1, 'MH14XY7890', 'van', 14.0, 'petrol');

INSERT INTO route(from_city, to_city, path, total_distance, total_fuel_l, total_emission, algorithm_used) VALUES
    ('Hyderabad', 'Delhi', 'Hyderabad → Nagpur → Delhi', 1550.0, 193.75, 418.50, 'FASTEST');
